spring:
  application:
    name: manito-server

  datasource:
    url: ENC(HdNhdC5xTKlFn8h1+VaJwgRRG01t16bzHVOeX58NDwsTfL0ubiE2YIg5hkoS4UKg2RPOeIDa4gHaW0BycblL3seIjVTuL3MxZ0JcFIZ+pxuJGV1ZlGpqvlh92GoTcLCv)
    username: ENC(+O3FJaHZ0oMs3b65pJWlw0amfnJjSpj+VwRk+RmZ7fX/BhMGRt9U/CwzkELiY8LS)
    password: ENC(2KASpL3OVLDE/D9SZu220U5VRbXQmFAoeJuXjxveOvZAWxJjpfPsdJp6kREkFwt6)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    bean: jasyptEncryptor

jwt:
  secret-key: ENC(K5Ul43Ii9wg2hVUfUvULJriTnN/KzRIw/j23vJrmJ4r5j/8TOyJDdBVZ6dARircAmKaGG9Msvhqw5MbRi9gUfjLYCqLV+HUE7vJpOI0WWpc=)
  access-token:
    expiration-seconds: 86400 #1일
  refresh-token:
    expiration-seconds: 604800 #7일

oauth:
  kakao:
    client-id: ENC(ryNisESR51pLpLIek6sTNlxiwPY1Pnrqn22DBlbf8AjSa6oNHjxqOhuCUMuwo/HEngjUQf14XbPDnDumb/jTeCQvKT0z7uhZjcSmsEa23Uk=)
    redirect-url: ENC(vA5VCJSJCekDM59s/ZW7NRaTB7kAHI3sGy5bgP6kcQ/3021wUpDczyKo2xB2HzDQaYWjRKssLFwDqbTbPrz7EHETgBOs4OKz5WY+5YZz4xRBYs3nE0PrHH81OGxNavUW)